# Generated by Django 5.1.3 on 2025-01-20 17:08

from django.db import migrations
from django.contrib.auth.hashers import make_password

from authentication.serializers import generate_unique_user_code

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250120_1016'),
    ]

    def create_admin_user(apps, schema_editor):
        User = apps.get_model('authentication', 'User')
        Role = apps.get_model('authentication', 'Role')
        # Créez l'utilisateur admin s'il n'existe pas déjà
        if not User.objects.filter(email='admin@gmail.com').exists():
            admin_role = Role.objects.filter(libelle="ADMINISTRATEUR").first()

            admin_user = User(
                username='admin@gmail.com',
                last_name="Admin",  
                first_name="Admin",
                email='admin@gmail.com',
                role=admin_role,
                password=make_password('#!@dm1n!#'),
                user_code = generate_unique_user_code()
            )
            admin_user.save()
            
    def create_user(apps, schema_editor):
        User = apps.get_model('authentication', 'User')
        Role = apps.get_model('authentication', 'Role')
        # Créez l'utilisateur admin s'il n'existe pas déjà
        if not User.objects.filter(email='auser@gmail.com').exists():
            admin_role = Role.objects.filter(libelle="USER").first()

            admin_user = User(
                username='user@gmail.com',
                last_name="AdmUSerin",  
                first_name="Admin",
                email='auser@gmail.com',
                role=admin_role,
                password=make_password('#!@dm1n!#'),
                user_code = generate_unique_user_code()
            )
            admin_user.save()
    
    operations = [
        migrations.RunPython(create_admin_user),
        migrations.RunPython(create_user)
    ]
