# Generated by Django 5.1.3 on 2025-03-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250120_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notification_actif',
            field=models.BooleanField(default=True),
        ),
    ]
